<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="autonomous_wheelchair">

  <!-- Include Gazebo plugins -->
  <xacro:include filename="$(find wheelchair_description)/urdf/wheelchair.gazebo.xacro" />
  
  <!-- Include ros2_control description (DISABLED - using direct Gazebo plugin instead) -->
  <!-- Uncomment below to re-enable ros2_control if needed -->
  <!-- <xacro:include filename="$(find wheelchair_description)/urdf/wheelchair.ros2_control.xacro" /> -->

  <!-- ==================== PARAMETERS ==================== -->
  <xacro:property name="base_length" value="0.50"/>
  <xacro:property name="base_width" value="0.44"/>
  <xacro:property name="base_height" value="0.05"/>
  <xacro:property name="base_mass" value="10.0"/>
  
  <!-- Computed box inertial for chassis -->
  <!-- For box: I = m/12 * (dim1² + dim2²) -->
  <!-- h = 0.05, w = 0.44, l = 0.5, m = 10.0 -->
  <!-- h² = 0.05² = 0.0025, w² = 0.44² = 0.1936, l² = 0.5² = 0.25 -->
  <!-- Ixx = (10/12) * (0.0025 + 0.1936) = 0.16341666666666668 -->
  <!-- Iyy = (10/12) * (0.25 + 0.0025) = 0.21041666666666667 -->
  <!-- Izz = (10/12) * (0.25 + 0.1936) = 0.3696666666666667 -->
  <xacro:property name="Ixx_val" value="0.16341666666666668"/>
  <xacro:property name="Iyy_val" value="0.21041666666666667"/>
  <xacro:property name="Izz_val" value="0.3696666666666667"/>
  
  <!-- ==================== WHEEL PARAMETERS ==================== -->
  <!-- Consistent naming: back/front refer to position, left/right refer to side -->
  <xacro:property name="wheel_radius_back" value="0.15"/>      <!-- Back wheel radius (m) -->
  <xacro:property name="wheel_width_back" value="0.04"/>        <!-- Back wheel width (m) -->
  <xacro:property name="wheel_radius_front" value="0.095"/>     <!-- Front wheel radius (m) -->
  <xacro:property name="wheel_width_front" value="0.03"/>      <!-- Front wheel width (m) -->
  <xacro:property name="wheel_mass" value="0.5"/>                <!-- Wheel mass (kg) -->
  <!--
    Front wheel mount drop (distance from base_uplayer_link origin down to front wheel center).
    We pick this so that both front and back wheels touch the ground with the SAME spawn z.

    Back wheel bottom z:
      z_bottom_back = z_spawn + base_height_offset - 2 * wheel_radius_back
    For wheels to touch ground: z_bottom_back = 0  =>  z_spawn = 2*R_back - base_height_offset
      With R_back = 0.15, base_height_offset = 0.21:  z_spawn = 0.30 - 0.21 = 0.09 m

    For the front wheel (radius R_front) at the same z_spawn, we want:
      z_bottom_front = z_spawn + base_height_offset - wheel_front_mount_height - R_front = 0
      => wheel_front_mount_height = z_spawn + base_height_offset - R_front
      = 0.09 + 0.21 - 0.095 = 0.205 m

    So the front wheel center hangs 0.205 m below the base origin, and the wheel radius
    is 0.095 m, giving an 11 cm “metal fork” / spacer which visually raises the chair front.
  -->
  <xacro:property name="wheel_front_mount_height" value="0.205"/>
  
  <!-- Wheel separation distances (relative to base_uplayer_link) -->
  <xacro:property name="wheel_separation_longitudinal" value="0.5"/>   <!-- Distance between front and back wheels (m) -->
  <xacro:property name="wheel_separation_lateral" value="0.52"/>      <!-- Distance between left and right wheels (m) -->
  <xacro:property name="wheel_base_x" value="0.25"/>                  <!-- Half of longitudinal separation (m) -->
  <xacro:property name="wheel_base_y" value="0.26"/>                  <!-- Half of lateral separation (m) -->
  
  <!-- For diff drive calculations: use lateral separation -->
  <xacro:property name="wheel_separation" value="0.52"/>              <!-- Lateral separation for diff drive (m) -->
  
  <!-- Base link height offset -->
  <xacro:property name="base_height_offset" value="0.21"/>

  <!-- ==================== BASE FRAME (chassis) ==================== -->
  <!-- Note: Original had no inertial, but Gazebo Fortress requires it -->
  <link name="chassis">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <material name="transparent">
        <color rgba="0.0 0.0 0.0 0.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <inertia
        ixx="${Ixx_val}" ixy="0.0" ixz="0.0"
        iyy="${Iyy_val}" iyz="0.0"
        izz="${Izz_val}"/>
    </inertial>
  </link>

  <!-- ==================== BASE UPPER LINK (main platform) ==================== -->
  <link name="base_uplayer_link">
    <visual name="chassis_visual">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <!-- Using computed box inertia values (same as chassis since same dimensions) -->
      <inertia
        ixx="${Ixx_val}" ixy="0" ixz="0"
        iyy="${Iyy_val}" iyz="0"
        izz="${Izz_val}"/>
    </inertial>

    <collision name="collision">
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <collision name="caster_collision">
      <origin xyz="-0.2 0.0 -0.05" rpy="0.0 0.0 0.0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <visual name="caster_visual">
      <origin xyz="-0.2 0.0 -0.05" rpy="0.0 0.0 0.0"/>  <!-- Match collision position -->
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>
  </link>

  <joint name="base_joint" type="fixed">
    <origin xyz="0.0 0.0 ${base_height_offset}" rpy="0.0 0.0 0.0"/>
    <parent link="chassis"/>
    <child link="base_uplayer_link"/>
  </joint>

  <!-- ==================== WHEELS ==================== -->
  <!-- Wheel macro for back wheels -->
  <xacro:macro name="wheel_back" params="name x y">
    <link name="${name}_link">
      <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="${wheel_mass}"/>
        <!-- For cylinder: Ixx = Iyy = m/12 * (3*r² + h²), Izz = m*r²/2 -->
        <!-- Back wheel: r=0.15, h=0.04, m=0.5 -->
        <!-- Ixx = Iyy = 0.5/12 * (3*0.0225 + 0.0016) = 0.0029 -->
        <!-- Izz = 0.5 * 0.0225 / 2 = 0.0056 -->
        <inertia ixx="0.0029" ixy="0.0" ixz="0.0" iyy="0.0029" iyz="0.0" izz="0.0056"/>
      </inertial>
      <visual name="${name}_visual">
        <origin xyz="0.0 0.0 0.0" rpy="1.57079632679 0.0 0.0"/>  <!-- π/2 rotation for cylinder -->
        <geometry>
          <cylinder length="${wheel_width_back}" radius="${wheel_radius_back}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision name="${name}_collision">
        <origin xyz="0.0 0.0 0.0" rpy="1.57079632679 0.0 0.0"/>  <!-- π/2 rotation for cylinder -->
        <geometry>
          <cylinder length="${wheel_width_back}" radius="${wheel_radius_back}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_joint" type="continuous">
      <!-- Wheel center should be at negative wheel radius below base_uplayer_link center -->
      <!-- This positions the wheel so it touches the ground -->
      <origin xyz="${x} ${y} -${wheel_radius_back}" rpy="0.0 0.0 0.0"/>
      <parent link="base_uplayer_link"/>
      <child link="${name}_link"/>
      <axis xyz="0.0 1.0 0.0"/>
    </joint>
  </xacro:macro>

  <!-- Wheel macro for front wheels (modeled as casters: yaw joint + wheel roll joint) -->
  <xacro:macro name="wheel_front" params="name x y">
    <!-- Caster mount link (small metal fork under the base) -->
    <link name="${name}_caster_link">
      <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="0.2"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
      <visual name="${name}_caster_visual">
        <!-- Simple vertical bar representing the metal support -->
        <origin xyz="0.0 0.0 -${wheel_front_mount_height * 0.5}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="0.02 0.02 ${wheel_front_mount_height}"/>
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision name="${name}_caster_collision">
        <origin xyz="0.0 0.0 -${wheel_front_mount_height * 0.5}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <box size="0.02 0.02 ${wheel_front_mount_height}"/>
        </geometry>
      </collision>
    </link>

    <!-- Wheel link (same as before, attached to caster link instead of base) -->
    <link name="${name}_link">
      <inertial>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <mass value="${wheel_mass}"/>
        <!-- For cylinder: Ixx = Iyy = m/12 * (3*r² + h²), Izz = m*r²/2 -->
        <!-- Front wheel: r=0.095, h=0.03, m=0.5 -->
        <!-- Ixx = Iyy = 0.5/12 * (3*0.009025 + 0.0009) = 0.0012 -->
        <!-- Izz = 0.5 * 0.009025 / 2 = 0.0023 -->
        <inertia ixx="0.0012" ixy="0.0" ixz="0.0" iyy="0.0012" iyz="0.0" izz="0.0023"/>
      </inertial>
      <visual name="${name}_visual">
        <origin xyz="0.0 0.0 0.0" rpy="1.57079632679 0.0 0.0"/>  <!-- π/2 rotation for cylinder -->
        <geometry>
          <cylinder length="${wheel_width_front}" radius="${wheel_radius_front}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision name="${name}_collision">
        <origin xyz="0.0 0.0 0.0" rpy="1.57079632679 0.0 0.0"/>  <!-- π/2 rotation for cylinder -->
        <geometry>
          <cylinder length="${wheel_width_front}" radius="${wheel_radius_front}"/>
        </geometry>
      </collision>
    </link>

    <!-- Caster yaw joint: base -> caster link (rotation about Z) -->
    <joint name="${name}_caster_yaw_joint" type="continuous">
      <origin xyz="${x} ${y} 0.0" rpy="0.0 0.0 0.0"/>
      <parent link="base_uplayer_link"/>
      <child link="${name}_caster_link"/>
      <axis xyz="0.0 0.0 1.0"/>
      <dynamics damping="0.1" friction="0.0"/>
      <limit effort="10.0" velocity="10.0"/>
    </joint>

    <!-- Wheel roll joint: caster link -> wheel (rotation about Y) -->
    <joint name="${name}_joint" type="continuous">
      <!-- Place the wheel center below the caster mount by wheel_front_mount_height -->
      <origin xyz="0.0 0.0 -${wheel_front_mount_height}" rpy="0.0 0.0 0.0"/>
      <parent link="${name}_caster_link"/>
      <child link="${name}_link"/>
      <axis xyz="0.0 1.0 0.0"/>
      <dynamics damping="0.0" friction="0.0"/>
      <limit effort="50.0" velocity="50.0"/>
    </joint>
  </xacro:macro>

  <!-- ==================== WHEEL INSTANTIATION ==================== -->
  <!-- Consistent naming convention:
       - wheel1: back_right_wheel (back right)
       - wheel2: back_left_wheel  (back left)
       - wheel3: front_right_wheel (front right)
       - wheel4: front_left_wheel  (front left)
       Joint names: wheel1_joint, wheel2_joint, wheel3_joint, wheel4_joint
       Link names: wheel1_link, wheel2_link, wheel3_link, wheel4_link
  -->
  <xacro:wheel_back name="wheel1" x="-${wheel_base_x}" y="-${wheel_base_y}"/>  <!-- Back Right -->
  <xacro:wheel_back name="wheel2" x="-${wheel_base_x}" y="${wheel_base_y}"/>     <!-- Back Left -->
  <xacro:wheel_front name="wheel3" x="${wheel_base_x}" y="-${wheel_base_y}"/>    <!-- Front Right -->
  <xacro:wheel_front name="wheel4" x="${wheel_base_x}" y="${wheel_base_y}"/>    <!-- Front Left -->

  <!-- ==================== IMU SENSOR ==================== -->
  <link name="imu_sensor_link">
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <inertia ixx="0.00000015" ixy="0.0" ixz="0.0" iyy="0.00000015" iyz="0.0" izz="0.00000015"/>
    </inertial>
  </link>

  <joint name="imu_sensor_joint" type="fixed">
    <origin xyz="0.0 0.0 0.23" rpy="0.0 0.0 0.0"/>
    <parent link="chassis"/>
    <child link="imu_sensor_link"/>
  </joint>

  <!-- ==================== CAMERA STAND & CAMERA ==================== -->
  <link name="camera_stand_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.05 0.05 0.435"/>
      </geometry>
      <material name="gray">
        <color rgba="0.2 1.0 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.05 0.04 0.435"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_stand_joint" type="fixed">
    <!-- Position: base top is at z=0.235m (0.21 + 0.025), stand center should be at base top + half stand height -->
    <!-- Stand height = 0.435m, so center = 0.235 + 0.2175 = 0.4525m -->
    <origin xyz="-0.22 0.0 0.4525" rpy="0.0 0.0 0.0"/>
    <parent link="chassis"/>
    <child link="camera_stand_link"/>
  </joint>

  <!-- Camera Link -->
  <link name="camera_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
      <visual name="camera_visual">
      <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.1 0.2 0.04"/>
      </geometry>
      <material name="camera_material">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.03" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.1 0.2 0.04"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="camera_stand_link"/>
    <child link="camera_link"/>
    <!-- Camera at top of stand: stand center is at z=0.4525, stand extends to z=0.4525+0.2175=0.67 -->
    <!-- Camera should be at top of stand, so position at stand top + half camera height -->
    <!-- Camera height = 0.04m, so center = 0.67 + 0.02 = 0.69m from stand center -->
    <!-- But wait, stand center is at 0.4525, stand top is at 0.4525+0.2175=0.67 -->
    <!-- Camera center should be at stand top + half camera height = 0.67 + 0.02 = 0.69 -->
    <!-- Relative to stand center: 0.69 - 0.4525 = 0.2375 -->
    <origin xyz="0.0 0.0 0.2375" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- Kinect Optical Frame -->
  <joint name="kinect_optical_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="-1.57079632679 0.0 -1.57079632679"/>  <!-- -π/2, 0, -π/2 -->
    <parent link="camera_link"/>
    <child link="kinect_optical"/>
  </joint>

  <link name="kinect_optical">
    <!-- Kinect optical frame - minimal link for TF tree (no visual/collision needed) -->
    <inertial>
      <mass value="0.0001"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <inertia
        ixx="0.00000001" ixy="0.0" ixz="0.0"
        iyy="0.00000001" iyz="0.0"
        izz="0.00000001"/>
    </inertial>
  </link>

  <!-- ==================== LIDAR SENSOR ==================== -->
  <link name="base_laser">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>  <!-- Aligned with collision -->
      <geometry>
        <cylinder length="0.05" radius="0.05"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.2 0.1 0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
    </inertial>
  </link>

  <joint name="base_link_to_lidar" type="fixed">
    <parent link="back_link"/>
    <child link="base_laser"/>
    <!-- Position: Lidar mounted on back bar at lower height -->
    <!-- Back bar is a box: 0.04 x 0.41 x 0.41 (width x height x depth) -->
    <!-- Back bar center is at z=0, extends from z=-0.205 to z=+0.205 -->
    <!-- Place lidar at lower position: z = 0.0 (center height) for better obstacle detection -->
    <!-- Position slightly forward (x positive) to clear the back bar surface -->
    <origin xyz="0.02 0.0 0.0" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- ==================== STRUCTURAL COMPONENTS (simplified) ==================== -->
  <!-- Note: Keeping essential structure, can add more details later if needed -->
  <!-- Seat link -->
  <link name="seat_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.4 0.5 0.04"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.4 0.5 0.04"/>
      </geometry>
    </collision>
  </link>

  <joint name="seat_joint" type="fixed">
    <origin xyz="-0.04 0.0 0.25" rpy="0.0 0.0 0.0"/>
    <parent link="base_uplayer_link"/>
    <child link="seat_link"/>
  </joint>

  <!-- Back link -->
  <link name="back_link">
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.04 0.41 0.41"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.02 0.41 0.41"/>
      </geometry>
    </collision>
  </link>

  <joint name="back_joint" type="fixed">
    <origin xyz="-0.2 0.0 0.22" rpy="0.0 0.0 0.0"/>
    <parent link="seat_link"/>
    <child link="back_link"/>
  </joint>

</robot>

